/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

/**
 *
 * @author onad
 */
public class exam extends javax.swing.JFrame {

    /**
     * Creates new form exam
     */
    public exam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    double total_price = 0, pizza_price = 0;
    String pizza_flavor = "HAWAIIAN", pizza_size = "SMALL";
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rb_flavor_hawaiian = new javax.swing.JRadioButton();
        rb_flavor_hamcheese = new javax.swing.JRadioButton();
        rb_flavor_peperroni = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        rb_size_small = new javax.swing.JRadioButton();
        rb_size_large = new javax.swing.JRadioButton();
        lbl_price_medium = new javax.swing.JLabel();
        lbl_price_small = new javax.swing.JLabel();
        lbl_price_large = new javax.swing.JLabel();
        rb_size_medium = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        button_createorder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PIZZA ORDERING SYSTEM");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rb_flavor_hawaiian);
        rb_flavor_hawaiian.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        rb_flavor_hawaiian.setSelected(true);
        rb_flavor_hawaiian.setText("HAWAIIAN");
        rb_flavor_hawaiian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_flavor_hawaiianActionPerformed(evt);
            }
        });
        jPanel1.add(rb_flavor_hawaiian, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        buttonGroup1.add(rb_flavor_hamcheese);
        rb_flavor_hamcheese.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        rb_flavor_hamcheese.setText("HAM AND CHEESE");
        rb_flavor_hamcheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_flavor_hamcheeseActionPerformed(evt);
            }
        });
        jPanel1.add(rb_flavor_hamcheese, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, -1));

        buttonGroup1.add(rb_flavor_peperroni);
        rb_flavor_peperroni.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        rb_flavor_peperroni.setText("PEPERRONI");
        rb_flavor_peperroni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_flavor_peperroniActionPerformed(evt);
            }
        });
        jPanel1.add(rb_flavor_peperroni, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 220, 100));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup2.add(rb_size_small);
        rb_size_small.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        rb_size_small.setSelected(true);
        rb_size_small.setText("SMALL-SIZED");
        rb_size_small.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_size_smallActionPerformed(evt);
            }
        });
        jPanel2.add(rb_size_small, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        buttonGroup2.add(rb_size_large);
        rb_size_large.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        rb_size_large.setText("LARGE-SIZED");
        rb_size_large.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_size_largeActionPerformed(evt);
            }
        });
        jPanel2.add(rb_size_large, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lbl_price_medium.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_price_medium.setText("110.00");
        jPanel2.add(lbl_price_medium, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 50, -1));

        lbl_price_small.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_price_small.setText("90.00");
        jPanel2.add(lbl_price_small, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 50, -1));

        lbl_price_large.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_price_large.setText("130.00");
        jPanel2.add(lbl_price_large, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 50, -1));

        buttonGroup2.add(rb_size_medium);
        rb_size_medium.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        rb_size_medium.setText("MEDIUM-SIZED");
        rb_size_medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_size_mediumActionPerformed(evt);
            }
        });
        jPanel2.add(rb_size_medium, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 220, 100));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        jCheckBox1.setText("EXTRA CHEESE");
        jPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, -1));

        jCheckBox2.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        jCheckBox2.setText("PEPPER");
        jPanel3.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, -1));

        jCheckBox3.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        jCheckBox3.setText("ONIONS");
        jPanel3.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, -1));

        jCheckBox4.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        jCheckBox4.setText("BLACK OLIVES");
        jPanel3.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, -1));

        jCheckBox5.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        jCheckBox5.setText("GREEN PEPPERS");
        jPanel3.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 220, 180));

        button_createorder.setText("CREATE ORDER");
        button_createorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_createorderActionPerformed(evt);
            }
        });
        getContentPane().add(button_createorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 180, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("PIZZA FLAVOR : \n\n\nPIZZA SIZE : \n\n\nADD ONS: \n\n\n\n\nTOTAL PRICE : ");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 280, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_flavor_hawaiianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_flavor_hawaiianActionPerformed
        // TODO add your handling code here:

        if (rb_flavor_hawaiian.isSelected()) {
            pizza_flavor = "HAWAIIAN";
            lbl_price_small.setText("90.00");
            lbl_price_medium.setText("110.00");
            lbl_price_large.setText("130.00");
        }
    }//GEN-LAST:event_rb_flavor_hawaiianActionPerformed

    private void rb_flavor_hamcheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_flavor_hamcheeseActionPerformed
        // TODO add your handling code here:
        if (rb_flavor_hamcheese.isSelected()) {
            pizza_flavor = "HAM AND CHEESE";
            lbl_price_small.setText("110.00");
            lbl_price_medium.setText("130.00");
            lbl_price_large.setText("150.00");
        }
    }//GEN-LAST:event_rb_flavor_hamcheeseActionPerformed

    private void rb_flavor_peperroniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_flavor_peperroniActionPerformed
        // TODO add your handling code here:
        if (rb_flavor_peperroni.isSelected()) {
            pizza_flavor = "PEPPERONI";
            lbl_price_small.setText("130.00");
            lbl_price_medium.setText("150.00");
            lbl_price_large.setText("170.00");
        }
    }//GEN-LAST:event_rb_flavor_peperroniActionPerformed

    private void button_createorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_createorderActionPerformed
        // TODO add your handling code here:
        if (rb_flavor_hawaiian.isSelected() && rb_size_small.isSelected())
        {
            pizza_price = 90;
        }
        if (rb_flavor_hawaiian.isSelected() && rb_size_medium.isSelected())
        {
            pizza_price = 110;
        }
        if (rb_flavor_hawaiian.isSelected() && rb_size_large.isSelected())
        {
            pizza_price = 130;
        }
        if (rb_flavor_hamcheese.isSelected() && rb_size_small.isSelected())
        {
            pizza_price = 110;
        }
        if (rb_flavor_hamcheese.isSelected() && rb_size_medium.isSelected())
        {
            pizza_price = 130;
        }
        if (rb_flavor_hamcheese.isSelected() && rb_size_large.isSelected())
        {
            pizza_price = 150;
        }
        if (rb_flavor_peperroni.isSelected() && rb_size_small.isSelected())
        {
            pizza_price = 130;
        }
        if (rb_flavor_peperroni.isSelected() && rb_size_medium.isSelected())
        {
            pizza_price = 150;
        }
        if (rb_flavor_peperroni.isSelected() && rb_size_large.isSelected())
        {
            pizza_price = 170;
        }
        jTextArea1.setText("PIZZA FLAVOR : " + pizza_flavor + "\n\n\nPIZZA SIZE : " + pizza_size + "\n\n\nADD ONS: \n\n\n\n\nTOTAL PRICE : " + pizza_price);
    }//GEN-LAST:event_button_createorderActionPerformed

    private void rb_size_smallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_size_smallActionPerformed
        // TODO add your handling code here:
        pizza_size = "SMALL";
    }//GEN-LAST:event_rb_size_smallActionPerformed

    private void rb_size_mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_size_mediumActionPerformed
        // TODO add your handling code here:
        pizza_size = "MEDIUM";
    }//GEN-LAST:event_rb_size_mediumActionPerformed

    private void rb_size_largeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_size_largeActionPerformed
        // TODO add your handling code here:
        pizza_size = "LARGE";
    }//GEN-LAST:event_rb_size_largeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton button_createorder;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_price_large;
    private javax.swing.JLabel lbl_price_medium;
    private javax.swing.JLabel lbl_price_small;
    private javax.swing.JRadioButton rb_flavor_hamcheese;
    private javax.swing.JRadioButton rb_flavor_hawaiian;
    private javax.swing.JRadioButton rb_flavor_peperroni;
    private javax.swing.JRadioButton rb_size_large;
    private javax.swing.JRadioButton rb_size_medium;
    private javax.swing.JRadioButton rb_size_small;
    // End of variables declaration//GEN-END:variables
}
