
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author onad
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        flavor_panel = new javax.swing.JPanel();
        flavor_hawaian = new javax.swing.JRadioButton();
        flavor_ham = new javax.swing.JRadioButton();
        flavor_pineapple = new javax.swing.JRadioButton();
        button_order = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        size_panel = new javax.swing.JPanel();
        size_small = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        size_medium = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        size_large = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        order_summary = new javax.swing.JTextArea();
        size_label = new javax.swing.JLabel();
        flavor_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flavor_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, null));
        flavor_panel.setLayout(new java.awt.GridLayout(4, 0));

        buttonGroup1.add(flavor_hawaian);
        flavor_hawaian.setText("Hawaian");
        flavor_hawaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flavor_hawaianActionPerformed(evt);
            }
        });
        flavor_panel.add(flavor_hawaian);

        buttonGroup1.add(flavor_ham);
        flavor_ham.setText("ham");
        flavor_ham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flavor_hamActionPerformed(evt);
            }
        });
        flavor_panel.add(flavor_ham);

        buttonGroup1.add(flavor_pineapple);
        flavor_pineapple.setText("pineapple");
        flavor_pineapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flavor_pineappleActionPerformed(evt);
            }
        });
        flavor_panel.add(flavor_pineapple);

        getContentPane().add(flavor_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 97, 92));

        button_order.setText("order");
        button_order.setActionCommand("CREATE \\n ORDER");
        button_order.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_order.setMargin(new java.awt.Insets(0, 14, 0, 14));
        button_order.setMaximumSize(new java.awt.Dimension(83, 0));
        button_order.setMinimumSize(new java.awt.Dimension(83, 0));
        button_order.setPreferredSize(new java.awt.Dimension(83, 0));
        button_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_orderActionPerformed(evt);
            }
        });
        getContentPane().add(button_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, 20));

        jPanel2.setLayout(new java.awt.GridLayout(4, 0, 2, 2));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        size_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, null));
        size_panel.setLayout(new java.awt.GridLayout(3, 2));

        buttonGroup2.add(size_small);
        size_small.setText("small");
        size_small.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size_smallActionPerformed(evt);
            }
        });
        size_panel.add(size_small);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("130");
        size_panel.add(jLabel1);

        buttonGroup2.add(size_medium);
        size_medium.setText("medium");
        size_medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size_mediumActionPerformed(evt);
            }
        });
        size_panel.add(size_medium);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("150");
        size_panel.add(jLabel2);

        buttonGroup2.add(size_large);
        size_large.setText("large");
        size_large.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size_largeActionPerformed(evt);
            }
        });
        size_panel.add(size_large);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("170");
        size_panel.add(jLabel3);

        getContentPane().add(size_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, 90));

        order_summary.setColumns(20);
        order_summary.setRows(5);
        jScrollPane1.setViewportView(order_summary);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        size_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        size_label.setText("SELECT SIZE");
        getContentPane().add(size_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 96, 21));

        flavor_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        flavor_label.setText("FLAVOR");
        getContentPane().add(flavor_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 93, 22));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flavor_pineappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flavor_pineappleActionPerformed
        pizzaFlavor = "Pineapple";
        // TODO add your handling code here:
    }//GEN-LAST:event_flavor_pineappleActionPerformed

    private void flavor_hamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flavor_hamActionPerformed
        pizzaFlavor = "Ham";
        // TODO add your handling code here:
    }//GEN-LAST:event_flavor_hamActionPerformed

    private void flavor_hawaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flavor_hawaianActionPerformed

        pizzaFlavor = "Hawaian";
        // TODO add your handling code here:
    }//GEN-LAST:event_flavor_hawaianActionPerformed

    private void size_largeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size_largeActionPerformed
        pizzaSize = "Large";
        // TODO add your handling code here:
    }//GEN-LAST:event_size_largeActionPerformed

    private void size_mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size_mediumActionPerformed
        pizzaSize = "Medium";
        // TODO add your handling code here:
    }//GEN-LAST:event_size_mediumActionPerformed

    private void size_smallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size_smallActionPerformed
        pizzaSize = "Small";
        // TODO add your handling code here:
    }//GEN-LAST:event_size_smallActionPerformed

    private void button_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_orderActionPerformed
        
        order_summary.setText(
            "PIZZA FLAVOR: " + pizzaFlavor +
            "\n\n" + " PIZZA SIZE: " + pizzaSize +
            " \n\n ");
//        int response = JOptionPane.showConfirmDialog(null, "Confirm Order", "WARNING", JOptionPane.OK_CANCEL_OPTION);
//        if(response == JOptionPane.OK_OPTION){
//            JOptionPane.showMessageDialog(null, "Ordered Succesfully");
//        }
// TODO add your handling code here:
    }//GEN-LAST:event_button_orderActionPerformed
    String pizzaFlavor,pizzaSize;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton button_order;
    private javax.swing.JRadioButton flavor_ham;
    private javax.swing.JRadioButton flavor_hawaian;
    private javax.swing.JLabel flavor_label;
    private javax.swing.JPanel flavor_panel;
    private javax.swing.JRadioButton flavor_pineapple;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea order_summary;
    private javax.swing.JLabel size_label;
    private javax.swing.JRadioButton size_large;
    private javax.swing.JRadioButton size_medium;
    private javax.swing.JPanel size_panel;
    private javax.swing.JRadioButton size_small;
    // End of variables declaration//GEN-END:variables
}
